apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}-pg
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  ports:
  - name: ${project.artifactId}-pg
    port: 35432
    targetPort: 35432
  selector:
    app: ${project.artifactId}
