CREATE DATABASE demo OPTIONS (ANNOTATION 'Demo VDB');
USE DATABASE demo;

CREATE FOREIGN DATA WRAPPER "sap-gateway";
CREATE SERVER sapdb TYPE 'NONE' FOREIGN DATA WRAPPER "sap-gateway";
CREATE SCHEMA sap SERVER sapdb;

SET SCHEMA sap;
IMPORT FOREIGN SCHEMA public FROM SERVER sapdb INTO sap;
